Repository UNLV-CS472-672/2025-S-GROUP5-ISIT, pull requests merged in 2025-03, with the labels that each got.

#17 Init - Profile Page
  .idea/misc.xml
  app/src/main/java/com/example/ingrediscan/ui/profile/ProfileFragment.kt
  app/src/main/java/com/example/ingrediscan/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/example/ingrediscan/ui/profile/Utilities.kt
  app/src/main/res/drawable/test_logo.png
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: FE

#25 Added User and User Profile classes
  app/build.gradle.kts
  app/src/main/java/com/example/ingrediscan/model/Email.kt
  app/src/main/java/com/example/ingrediscan/model/Password.kt
  app/src/main/java/com/example/ingrediscan/model/User.kt
  app/src/main/java/com/example/ingrediscan/model/UserProfile.kt
  app/src/main/java/com/example/ingrediscan/model/WeightLog.kt
Labels: BE

#31 Create ScannedItem class. Add a list of scanned data into user.kt
  app/src/main/java/com/example/ingrediscan/model/ScannedItem.kt
  app/src/main/java/com/example/ingrediscan/model/User.kt
Labels: BE, HI

#30 Refactoring of OCR function, Added barcode Scanner function, and crea…
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/example/ingrediscan/BackEnd/TextRecognition/TextRecognition.kt
  app/src/test/java/com/example/ingrediscan/BackEnd/TextRecognition/TextRecognitionHelperTest.kt
  gradle/libs.versions.toml
Labels: BE, HI
