Repository UNLV-CS472-672/2025-S-GROUP5-ISIT, pull requests merged in 2025-04, with the labels that each got.

#51 Updated search page UI and functionality
  app/build.gradle.kts
  app/src/main/java/com/example/ingrediscan/ui/search/MarkerView.kt
  app/src/main/java/com/example/ingrediscan/ui/search/Result.kt
  app/src/main/java/com/example/ingrediscan/ui/search/SearchFragment.kt
  app/src/main/res/drawable/marker_background.xml
  app/src/main/res/drawable/search_outline.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/marker_view.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: FE

#57 CameraX preview and previous results UI tweaks
  app/src/main/java/com/example/ingrediscan/MainActivity.kt
  app/src/main/java/com/example/ingrediscan/ui/previous_results/PreviousResultsScreen.kt
  app/src/main/java/com/example/ingrediscan/ui/previous_results/PreviousResultsViewModel.kt
  app/src/main/java/com/example/ingrediscan/ui/scan/ScanScreen.kt
  app/src/main/java/com/example/ingrediscan/ui/theme/Color.kt
Labels: FE, BE, HI

#59 Add Login page on MainActivity
  app/src/main/java/com/example/ingrediscan/MainActivity.kt
  app/src/main/java/com/example/ingrediscan/ui/login/LoginFragment.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
Labels: FE

#65 Remove status bar on top and Implement Create Account page UI
  app/src/main/java/com/example/ingrediscan/MainActivity.kt
  app/src/main/java/com/example/ingrediscan/ui/createAccount/CreateAccountFragment.kt
  app/src/main/java/com/example/ingrediscan/ui/createAccount/CreateAccountViewModel.kt
  app/src/main/java/com/example/ingrediscan/ui/login/LoginFragment.kt
  app/src/main/res/layout/fragment_create_account.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: FE

#77 Created dynamic layout of search results display
  app/src/main/java/com/example/ingrediscan/MainActivity.kt
  app/src/main/java/com/example/ingrediscan/ui/search/Result.kt
  app/src/main/java/com/example/ingrediscan/ui/search/SearchFragment.kt
  app/src/main/res/drawable/banana.jpg
  app/src/main/res/drawable/granola.jpg
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_result.xml
Labels: FE, Med

#82 Previous Results Now Acts as a History for Logged Meals
  app/src/main/java/com/example/ingrediscan/BackEnd/ApiCalls/ApiCalls.kt
  app/src/main/java/com/example/ingrediscan/ui/home/HomeFragment.kt
  app/src/main/java/com/example/ingrediscan/ui/logMealPage/LogMealBySearchViewModel.kt
  app/src/main/java/com/example/ingrediscan/ui/previous_results/PreviousResultsViewModel.kt
Labels: FE, BE

#88 Created new detailed search result page.
  .gitignore
  app/src/main/java/com/example/ingrediscan/ui/search/SearchFragment.kt
  app/src/main/java/com/example/ingrediscan/ui/search/SearchResult.kt
  app/src/main/java/com/example/ingrediscan/ui/searchDetailPage/SearchDetailFragment.kt
  app/src/main/java/com/example/ingrediscan/ui/searchDetailPage/SearchDetailViewModel.kt
  app/src/main/res/layout/fragment_search_detail.xml
  app/src/main/res/navigation/mobile_navigation.xml
  gradlew
Labels: FE

#92 Results changes and improvements
  app/src/main/java/com/example/ingrediscan/ui/previous_results/PreviousResultsScreen.kt
Labels: FE, LO
